apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned-pod
  namespace: demo
  labels:
    owner: huan
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: app
    image: nginx:1.25.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
