apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Chạy sau khi Gatekeeper controller đã được cài đặt (wave -1)
spec:
  project: default
  source:
    repoURL: https://github.com/huynhhuan/bahuan-aws-accelerator-p2.git
    path: cloud/W10/lab/gatekeeper
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
