apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-slo
  namespace: demo
  labels:
    app: api
spec:
  groups:
    - name: api.slo
      rules:
        - record: api:success_rate:5m
          expr: |
            sum(rate(flask_http_request_total{namespace="demo",status!~"5.."}[5m]))
            /
            sum(rate(flask_http_request_total{namespace="demo"}[5m]))

        - alert: ApiHighErrorRate
          expr: api:success_rate:5m < 0.95
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "API success rate below 95%"
            description: "API success rate is below SLO for more than 2 minutes."